import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/styles/global.scss';
import AntdRegistry from '@ant-design/nextjs-registry/lib/AntdRegistry';
import { AntdConfigProvider } from '@/theme/antd-config/antd-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdConfigProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </AntdConfigProvider>
      </body>
    </html>
  );
}
